services:
  api:
    build: .    # Нужен Dockerfile из текущей папки (!!! Нужен путь до ПАПКИ, не до файла!!!)
    container_name: fastapi-app
    ports:
      - "8000:8000"   # хост:контейнер
    volumes:
      - .:/app    # Hot reload для разработки
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload